### ISSUE TITLE
Forward request: unable to pass "Host" header

### ISSUE THREAD

**Issue by smartpcr** [Azure/service-fabric-aspnetcore#33]
I used reverse proxy to pass request from frontend to backend. Everything works ok with full .net framework. After changed to netcore2.0 with preview nuget packages, it returned "400 bad request: invalid hostname" error. Seems "Host" header cannot be forwarded.

code is [here] (https://github.com/smartpcr/SF-reverseproxy-test), master branch targets full framework, preview branch target netcore2.0.

**Comment by amanbha** [comment]
Which part of your sample code is returning 400. I see that you have a middleware, Are you able to debug and figure out what component is causing the failure? Does it works without your middleware?

**Comment by smartpcr** [comment]
within preview branch, ProxyMiddleware class, on line 56 (see snippet below), if header "Host" is skipped from copying, it will work.

using (HttpResponseMessage responseMessage = await _httpClient.SendAsync(requestMessage, HttpCompletionOption.ResponseHeadersRead, context.RequestAborted))
{
}

**Comment by amanbha** [comment]
To understand it better and narrow down the issue, , I have following questions:
1. Was SF runtime version different when you performed your 2 tests with full .net and and with .net core. What was the runtime version?
2. Is Reverse Proxy returning 400 or your service returning 400? You can see this by seeing events for  Reverse Proxy (https://docs.microsoft.com/en-us/azure/service-fabric/service-fabric-reverse-proxy-diagnostics)
3. Since SF Reverse Proxy is written in native code, so running on core should not affect its behavior, could you try it with calling it from a console exe using a full .net HttpClient and then with a net code HttpClient.

**Comment by amanbha** [comment]
@smartpcr i am closing the issue for now because of no updates, please feel free to reopen or file a new one if you need help with this. Thanks!
