### ISSUE TITLE
Template updates

### ISSUE THREAD

**Issue by SteveSandersonMS** [Azure/service-fabric-aspnetcore#55]
Hi there. Are the Service Fabric versions of the ASP.NET Core templates maintained in this repo? Or if not, can you point me to wherever they are currently maintained?

We have a customer report that the Service Fabric File-New path is still using the older ASP.NET Core templates (below). Who would be involved in updating this? Thanks.

-----

**Template not used when adding .net Core stateless service in Service Fabric**
Posted by @John-Bell
Moved from https://github.com/aspnet/JavaScriptServices/issues/1622

Hi

After installing the new templates dotnet new --install Microsoft.DotNet.Web.Spa.ProjectTemplates::2.0.0 the new Angular (angular-cli) version is used through Visual Studio,

However when adding a stateless .net core Service to a Service Fabric Application and selecting 'Angular', the older webpack based template is used.

**Comment by amanbha** [comment]
@SteveSandersonMS  This is not the repo for Service Fabric aspnetcore templates, @dbreshears can help with this.

**Comment by SteveSandersonMS** [comment]
Thanks @amanbha!

@dbreshears, could you let me know where the Service Fabric ASP.NET Core templates are maintained? What's the process/timeline for migrating updates from the original sources in https://github.com/aspnet/templating/?

**Comment by dbreshears** [comment]
@SteveSandersonMS, sorry for the delay, I was OOF.    The service templates use the built in  ASP.NET Core templates and after project creation, we do some post processing on them to add Web1.cs and update program1.cs.    Do you see the same issue if you simply  create an ASP.NET Core project without Service Fabric?

**Comment by John-Bell** [comment]
Hi @SteveSandersonMS and @dbreshears

Apologies, I was using dotnet new to create the angular template which used the new template.  You're right, using VS 15.7.1 to create a new .net core application via VS uses the old template.

So currently there's no easy way to add a new 'angular' Service Fabric service except to hand craft it from a project created with dotnet new. (Which is what I had to do).  

Note that the Service Fabric service won't allow for the angular-cli server to be used whilst running the service since service fabric publishes the files to another location but the template does enable the front end to be managed with the cli tools.

**Comment by mozts2005** [comment]
@dbreshears I have a custom asp.net core template that I would Like to use with Service fabric is there a way I can have it show in the visual studio ui just like the default templates and receive the same post-processing?

**Comment by dbreshears** [comment]
Sorry for the delay.  Yes,  here is a sample VSIX that worked in the 15.3 timeframe and should still work.  

[StatelessWebApi.zip](https://github.com/Microsoft/service-fabric-aspnetcore/files/2237490/StatelessWebApi.zip)

**Comment by mozts2005** [comment]
@dbreshears  worked like a charm thanks
